language: node_js
node_js:
  - '16.10.0'
dist: focal
services:
  - postgresql
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
before_script:
  - psql -c 'create database seiu503_member_app_test;' -U postgres
script:
  - echo "Running tests..."
after_success:
  - pip install awscli
  - echo "AWS CLI installed"
